name: install and cache dependencies
description: |
  This action installs and caches dependencies for a Node.js project using Yarn.

runs:
  using: "composite"
  steps:
    - name: Set up Nodejs
      uses: actions/setup-node@v4
      with:
        node-version: "22.16.0"
    - name: Cache node modules
      id: cache
      uses: actions/cache@v4
      with:
        path: |
          node_modules
          .yarn
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: yarn install
      shell: bash