name: Custom JavaScript Action
description: |
  This action runs a custom JavaScript script.
inputs:
  bucket:
    description: "The name of the S3 bucket to use"
    required: true
    type: string
  bucket-region:
    description: "The region of the S3 bucket"
    required: false
    default: "us-east-1"
    type: string
  dist-folder:
    description: "The folder to upload to the S3 bucket"
    required: true
    type: string
  outputs:
    website-url:
      description: "The URL of the deployed website"

runs:
  using: "node20"
  main: "main.js"