name: build
on:
  workflow_call:
    inputs:
      reqiured_steps:
        description: "Required steps to run before build"
        required: false
        type: string
    outputs:
      build_artifacts:
        description: "Build artifacts from the build job"
        value: ${{jobs.build.outputs.outcome}}

jobs:
  build:
    outputs:
      outcome: ${{ steps.set_output.outputs.build_artifacts }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cache node modules
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            .yarn
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Set up Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "22.16.0"
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install
      - name: Build project
        run: yarn build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build
      - name: Set output
        id: set_output
        run: echo "::set-output name=build_artifacts::build"
