name: Continue Workflow
on: workflow_dispatch
jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  test:
    uses: ./.github/workflows/test.yml
    with:
      continue: false

  build:
    uses: ./.github/workflows/build.yml
    with:
      reqiured_steps: "lint,test"
