name: Deployment
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  VITE_API_KEY: myProductionKey
  VITE_SENSITIVE_DATA: ${{ secrets.VITE_SENSITIVE_DATA }}

jobs:
  variable_check:
    env:
      VITE_STAGING_ENV_VARIABLE: ${{ secrets.VITE_STAGING_ENV_VARIABLE }}

    runs-on: ubuntu-latest
    steps:
      - name: Check environment variable
        run: echo "VITE_API_KEY is set to $VITE_API_KEY"
      - name: Check sensitive data
        run: echo "VITE_SENSITIVE_DATA is set to $VITE_SENSITIVE_DATA"
      - name: check staging environment variable
        run: echo "VITE_STAGING_ENV_VARIABLE is set to $VITE_STAGING_ENV_VARIABLE"

  staging_variable_check:
    environment: staging
    env:
      VITE_STAGING_ENV_VARIABLE: ${{ secrets.VITE_STAGING_ENV_VARIABLE }}
    runs-on: ubuntu-latest
    steps:
      - name: check staging environment variable
        run: echo "VITE_STAGING_ENV_VARIABLE is set to $VITE_STAGING_ENV_VARIABLE"

  test:
    env:
      VITE_JOB_ID: 123
    runs-on: ubuntu-latest
    steps:
      - name: Check environment variable
        run: echo "VITE_JOB_ID is set to $VITE_JOB_ID"
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cache node modules
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            .yarn
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Set up Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "22.16.0"
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install
      - name: Run linter
        run: yarn lint
      - name: Run tests
        id: run-tests
        run: yarn test

      - name: upload test artifacts
        if: failure() && steps.run-tests.outcome == 'failure'

        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: package.json

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Check environment variable
        run: echo "VITE_JOB_ID is set to $VITE_JOB_ID"
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cache node modules
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            .yarn
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Set up Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "22.16.0"
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install
      - name: Build project
        run: yarn build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: ./build
      - name: Display build artifacts
        run: ls
      - name: Check AWS credentials
        run: echo "AWS_ACCESS_KEY_ID is set to ${{ secrets.VITE_STAGING_ENV_VARIABLE }}" && echo "AWS_SECRET_ACCESS_KEY is set to ${{ secrets.AWS_SECRET_ACCESS_KEY }}"
      - name: Deploy to production
        env:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        uses: ./.github/actions/javascript-custom-action
        with:
          bucket: mgm-react-router-7
          region: us-east-1
          dist-folder: ./build

  report:
    needs: ["test"]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Display error message
        run: |
          echo "The tests failed. Please check the logs for more details."
          exit 1
