name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: print greaintg
        run: echo "Hello World"
      - name: print goodby
        run: echo "Goodbye"
      - name: Run custom JV action
        uses: ./.github/actions/javascript-custom-action
