name: Lint
on: workflow_call
jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: node:22.16.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: install dependencies
        uses: ./.github/actions/install_and_cache-dependencies
      - name: Run linter
        run: yarn lint
