name: Reuse Workflow
on: workflow_dispatch
jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  test:
    uses: ./.github/workflows/test.yml
    with:
      continue: false

  build:
    needs: [lint, test]
    uses: ./.github/workflows/build.yml

  print-deploy-result:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Print build artifacts
        run: echo "Build atrifact is ${{needs.build.outputs.build_artifacts}}"
