name: Test
on:
  workflow_call:
    inputs:
      continue:
        description: "Continue the workflow when errors are encountered"
        required: false
        default: false
        type: boolean
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: install dependencies
        uses: ./.github/actions/install_and_cache-dependencies
        with:
          node_install: false
      - name: Run tests
        continue-on-error: ${{ inputs.continue }}
        id: run-tests
        run: yarn test
